### ISSUE TITLE
Results on the EC dataset

### ISSUE THREAD

**Issue by nooralahzadeh** [rainarch/DSNER#2]
Hi,
I ran the train_DSNER_model_py on EC dataset, however the maximum measures that I get on dev dataset  is:
precision:  61.21%; recall:  48.84%; FB1:  54.33
In the paper you got  
precision:  62.31%; recall:  63.79%; FB1:  63.04

Did you set any special parameter in config which is different than the one in github?

**Comment by nooralahzadeh** [comment]
It seems by including the word_embedding path in the config file, the performance goes up!
Is it possible to put your final config file in the github?

**Comment by rainarch** [comment]
Thanks for your information.   The detailed config information is included in Config.py.
