### ISSUE TITLE
I implemented Pytorch version of your code

### ISSUE THREAD

**Issue by nooralahzadeh** [rainarch/DSNER#3]
Hi,
I implemented the Pytorch version of your code. if you are interested I  can send the link to put it in your GitHub!
I also have results of the experiments on EC dataset. It is promising.
Thanks

**Comment by rainarch** [comment]
Cool!!! Please send me the link. Thanks

**Comment by nooralahzadeh** [comment]
I just need to clean it up. When it is clean and ready will send you the link.

**Comment by nooralahzadeh** [comment]
Hi
Here is the code in Pytorch:
https://github.com/nooralahzadeh/DSNER-pytorch
I need to add some info regarding to the configuration in readme file!

**Comment by rainarch** [comment]
Have added a link to your project. Thanks.
